server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    auth_basic "QOpz.AI Guide";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        try_files $uri $uri/ =404;
    }
}
